### ISSUE TITLE
Deploy a website on Website.

### ISSUE THREAD

**Issue by ShweMoeThantAurum** [ShweMoeThantAurum/ContentManagementSystemGroupAssignmentTeam6#1]
Dear Zar, please deploy a website on WordPress. Make sure that your website is secure and stay alive.

**Comment by Myat-Pwint** [comment]
Yeah, you're so cool, Mr.issue one.

**Comment by Myat-Pwint** [comment]
You are cool.

**Comment by ZarChi123** [comment]
ok. will get it done

**Comment by ZarChi123** [comment]
just finished now!
